title: Hemanth Mandadi  # You can add your name here

logo: 1.PNG  # Use a relative path to the logo image

description: Cloud Automation Engineer specialized in AWS & DevOps. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

google_site_verification: "nE-yBDoWCj5TcTXXNcRBPPiJZxpC6pw5dEdeRo6kTCk" # Verify ownership through Search Console  

email: hemanthmandadi@gmail.com # Allow visitors to contact you
